CREATE TABLE  `bonafide_radni`.`nws_cat` (
`NWS_CAT_ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`NWS_CAT_NAME` VARCHAR( 128 ) NOT NULL
) ENGINE = INNODB CHARACTER SET utf8 COLLATE utf8_bin;

ALTER TABLE  `nws` ADD  `NWS_NWS_CAT_ID` INT NOT NULL ,
ADD INDEX (  `NWS_NWS_CAT_ID` );

INSERT INTO  `bonafide_radni`.`nws_cat` (
`NWS_CAT_ID` ,
`NWS_CAT_NAME`
)
VALUES (
NULL ,  'Aktualności'
);

ALTER TABLE  `nws` ENGINE = INNODB;

ALTER TABLE  `nws` ADD FOREIGN KEY (  `NWS_NWS_CAT_ID` ) REFERENCES  `bonafide_radni`.`nws_cat` (
`NWS_CAT_ID`
) ON DELETE RESTRICT ;

ALTER TABLE  `nws` CHANGE  `NWS_DATE`  `NWS_DATE` DATETIME NOT NULL