ALTER TABLE  `exp` ADD  `EXP_NAME` VARCHAR( 512 ) NULL;

TRUNCATE TABLE `nws_cat`;

INSERT INTO `nws_cat` (`NWS_CAT_ID`, `NWS_CAT_NAME`) VALUES
(1, 'Aktualności'),
(2, 'Akademia Monitoringu'),
(3, 'Strona - Kontakt'),
(4, 'Strona - O projekcie'),
(5, 'Strona - Wypowiedzi ekspertów'),
(6, 'Strona - Analiza wybranych uchwał'),
(7, 'Strona - Mieszkańcy konsultują'),
(8, 'Strona - Akademia Monitoringu');

INSERT INTO `nws` (`NWS_DATE`, `NWS_TITLE`, `NWS_CONTENT`, `NWS_NWS_CAT_ID`) VALUES
('2012-10-28 11:07:43', 'Kontakt', '<p>Anna Zetelman &ndash; koordynator projektu "Monitoring Radnych", <a href="mailto:anna.zetelman@bonafides.pl">anna.zetelman@bonafides.pl</a></p>\r\n<p>Katarzyna Jochymczyk &ndash; asystentka koordynatora projektu "Monitoring Radnych", <a href="mailto:kasia@bonafides.pl">kasia@bonafides.pl</a></p>\r\n<p>Karolina Sk&oacute;rka - asystentka koordynatora projektu "Monitoring Radnych", <a href="mailto:karolina@bonafides.pl">karolina@bonafides.pl</a></p>\r\n<p>Tel. (32)203-12-18</p>', 3),
('2012-10-28 11:22:09', 'O projekcie', '<p>Projekt "Monitoring Radnych" prowadzony jest przez Stowarzyszenie Wzajemnej Pomocy Bona Fides. Jego celem jest ciągły monitoring radnych Rady Miasta Katowice oraz przedstawianie wynik&oacute;w ich pracy.</p>\r\n<p>Bona Fides prowadzi stały monitoring radnych Rady Miasta Katowice od września 2009 r. Decyzja o jego podjęciu była wynikiem wielu docierających do stowarzyszenia sygnał&oacute;w od mieszkańc&oacute;w miasta, według kt&oacute;rych część radnych, mimo zamieszczenia na stronach BIP urzędu miasta grafiku, rzadko pojawiała się na swoich dyżurach. Początkowo monitoring objął jedynie dyżury radnych, jednak w trakcie jego realizacji podjęto decyzję o jego poszerzeniu i ukazaniu pracy radnych w szerszym kontekście.</p>\r\n<p>W ramach projektu stworzony został Indeks Aktywności Radnych, ukazujący obszary aktywności radnych takich jak: uczestnictwo w sesjach Rady Miasta, uczestnictwo w komisjach Rady Miasta, prowadzenie dyżur&oacute;w z mieszkańcami, prowadzenie i aktualizowanie strony internetowej oraz odpowiadanie na e-maile.</p>\r\n<p>W celu prezentacji prowadzonych przez Stowarzyszenie działań z zakresu monitoringu radnych powstała strona monitoringradnych.pl, na kt&oacute;rej na bieżąco można śledzić najważniejsze informacje dotyczące działalności Rady Miasta Katowice, podejmowanych decyzji i poszczeg&oacute;lnych radnych.</p>', 4),
('2012-10-28 11:31:09', 'Wypowiedzi ekspertów', '<p>W tym miejscu przedstawiane są analizy ekspert&oacute;w dotyczące r&oacute;żnych obszar&oacute;w funkcjonowania samorządu oraz por&oacute;wnanie uchwał i program&oacute;w funkcjonujących w Katowicach z ich odpowiednikami z innych miast. Liczymy, że część dobrych praktyk i rekomendacji przedstawionych przez ekspert&oacute;w uda się zaimplementować w Katowicach.</p>', 5),
('2012-10-28 11:31:38', 'Analiza wybranych uchwał', '<p>W zakładce prezentowane jest om&oacute;wienie najważniejszych, naszym zdaniem, uchwał powstających w mieście.&nbsp; Poza tekstem uchwały można się tu zapoznać z opiniami ekspert&oacute;w, radnych i dziennikarzy dotyczących danego zagadnienia.</p>', 6),
('2012-10-28 11:32:43', 'Mieszkańcy konsultują', '<p>Urząd Miasta Katowice prowadzi na internetowej Platformie Konsultacji Społecznych systematyczne konsultacje wszystkich uchwalanych w mieście akt&oacute;w prawa miejscowego. Konsultacje skierowane są jednak jedynie do organizacji pozarządowych. Nie mogą w nich wziąć udziału osoby prywatne. Uważamy, że warto w ten proces włączyć także mieszkańc&oacute;w, stąd w tej zakładce umieszczane są wszystkie obecnie organizowane przez urząd konsultacje. Osoby, kt&oacute;re chciałyby zgłosić swoje opinie i uwagi do projekt&oacute;w uchwał, mogą to zrobić za pośrednictwem naszego stowarzyszenia, wysyłając e-mail na adres: <a href="mailto:anna.zetelman@bonafides.pl">anna.zetelman@bonafides.pl</a></p>', 7),
('2012-10-28 11:49:19', 'Akademia Monitoringu', '<p>Akademia Monitoringu jest częścią projektu Monitoring Radnych, kt&oacute;ra poświęcona jest wsp&oacute;łpracy z wolontariuszami. Dzięki ich pomocy zbieramy informacje, kt&oacute;re możecie znaleźć w zakładce: Radni (m.in. rozliczenia z obietnic wyborczych, plany radnych na najbliższe miesiące). Wolontariusze Bona Fides prowadzą także monitoring obowiązk&oacute;w radnych: raz w miesiącu sprawdzają, czy chodzą na dyżury, co znajduje swoje odzwierciedlenie w Rankingu Radnych. Ponadto nasi wolontariusze uczestniczą także w comiesięcznych szkoleniach, gdzie poszerzają swoją wiedzę w zakresie temat&oacute;w takich jak: praca Rady Miasta, monitoring polityczny, community organizing, wolontariat europejski.</p>\r\n<p>Naszym celem jest zachęcenie jak największej ilości os&oacute;b do aktywnego uczestnictwa w życiu politycznym miasta, dlatego prowadzimy stały nab&oacute;r wolontariuszy. Jeśli jesteś zainteresowany uczestnictwem w Akademii Monitoringu skontaktuj się z nami mailowo: <a href="mailto:karolina@bonafides.pl">karolina@bonafides.pl</a> lub telefonicznie: (32)203-12-18.</p>', 8);
