INSERT INTO `radni`.`rdn` (`RDN_ID`, `RDN_FIRSTNAME`, `RDN_LASTNAME`, `RDN_EMAIL`, `RDN_PHONE`, `RDN_DUTY`, `RDN_WEBSITE`, `RDN_PHOTO`, `RDN_PROMISE`, `RDN_INTERVIEW`, `RDN_PROMISE_CMT`, `RDN_INTERVIEW_CMT`, `RDN_TNR_ID`, `RDN_OKR_ID`) 
VALUES
(NULL, 'Marek', 'Chmieliński', 'm.chmielinski@tlen.pl', '(0) 694-476-216', NULL, '-', '-', '-', '-', NULL, NULL, '1', '1'),
(NULL, 'Jerzy', 'Dolinkiewicz', 'jerzy.dolinkiewicz@um.katowice.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '4'),
(NULL, 'Jerzy', 'Forajter', 'jforajter@wp.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '2'),
(NULL, 'Stefan', 'Gierlotka', 'gierlotkastefan@interia.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '1'),
(NULL, 'Arkadiusz', 'Godlewski', 'poczta@arkadiuszgodlewski.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '4'),
(NULL, 'Tomasz', 'Godziek', 'tgodziek@gmail.com', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '1'),
(NULL, 'Helena', 'Hrapkiewicz', 'helena.hrapkiewicz@us.edu.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '3'),
(NULL, 'Michał', 'Jędrzejek', 'kontakt@jedrzejek.org', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '5'),
(NULL, 'Daria', 'Kosmala', 'poczta@dariakosmala.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '4'),
(NULL, 'Dariusz', 'Łyczko', 'dlyczko@op.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '2'),
(NULL, 'Tomasz', 'Maśnica', 'masnicaaa@interia.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '1'),
(NULL, 'Wiesław', 'Mrowiec', 'mrowiec.wieslaw@gmail.com', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '4'),
(NULL, 'Krystyna', 'Panek', 'k.panek@poczta.onet.eu', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '5'),
(NULL, 'Piotr', 'Pietrasz', 'pc_piotr@poczta.onet.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '3'),
(NULL, 'Bożena', 'Rojewska', 'kontakt@bozenarojewska.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '3'),
(NULL, 'Mariusz', 'Skiba', 'skiba@post.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '1'),
(NULL, 'Maria', 'Sokół', '-', '(0) 696-682-088', NULL, '-', '-', '-', '-', NULL, NULL, '1', '2'),
(NULL, 'Marek', 'Szczerbowski', 'marek.szczerbowski@um.katowice.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '5'),
(NULL, 'Tomasz', 'Szpyrka', 'Tomasz_Szpyrka@poczta.onet.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '3'),
(NULL, 'Adam', 'Warzecha', 'adam@warzecha.katowice.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '2'),
(NULL, 'Stanisława', 'Wermińska', 'stanislawa.werminska@poczta.onet.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '1'),
(NULL, 'Magdalena', 'Wieczorek', 'poczta@magdalenawieczorek.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '4'),
(NULL, 'Witold', 'Witkowicz', 'witold.witkowicz@gazeta.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '5'),
(NULL, 'Stanisław', 'Włoch', 'swloch@pron.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '1'),
(NULL, 'Barbara', 'Wnęk', 'poczta@barbarawnek.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '5'),
(NULL, 'Elżbieta', 'Zacher', 'elka.zacher@gmail.com', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '2'),
(NULL, 'Józef', 'Zawadzki', 'j.zawadzki@jzawadzki.nazwa.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '4'),
(NULL, 'Andrzej', 'Zydorowicz', 'andrzej@zydorowicz.pl', '-', NULL, '-', '-', '-', '-', NULL, NULL, '1', '3')

